# Generated by Django 6.0.7 on 2026-07-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=80)),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('version', models.CharField(blank=True, help_text='Ej: 1.6 5P Feline', max_length=120)),
                ('combustible', models.CharField(choices=[('nafta', 'Nafta'), ('gasoil', 'Gasoil'), ('gnc', 'GNC'), ('hibrido', 'Híbrido'), ('electrico', 'Eléctrico')], default='nafta', max_length=20)),
                ('transmision', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='manual', max_length=20)),
                ('kilometros', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('puertas', models.PositiveSmallIntegerField(default=4)),
                ('motor', models.CharField(blank=True, help_text='Ej: 1.6L 16v', max_length=60)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalles_desperfectos', models.TextField(blank=True, help_text='Detalles estéticos o mecánicos a informar al comprador.', verbose_name='Detalles / Desperfectos a reparar')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción general')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='autos_fotos/')),
                ('publicado', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Autos',
                'ordering': ['-destacado', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=150, verbose_name='Nombre y apellido')),
                ('marca', models.CharField(max_length=60, verbose_name='Marca del vehículo')),
                ('modelo', models.CharField(blank=True, max_length=80, verbose_name='Modelo del vehículo')),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('combustible', models.CharField(blank=True, choices=[('nafta', 'Nafta'), ('gasoil', 'Gasoil'), ('gnc', 'GNC')], max_length=20)),
                ('kilometros', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilómetros')),
                ('valor_pretendido', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor pretendido')),
                ('tiene_deudas', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=3, verbose_name='¿Contiene deudas?')),
                ('tiene_vtv', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=3, verbose_name='¿Contiene VTV/RTO?')),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('observaciones', models.TextField(blank=True, max_length=250, verbose_name='Observaciones')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('contactado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Propuesta de venta',
                'verbose_name_plural': 'Propuestas de venta',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='FotoAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='autos_fotos/galeria/')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='autos.auto')),
            ],
        ),
    ]
