# Generated by Django 6.0.7 on 2026-07-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestaventa',
            name='monto_infracciones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto de las infracciones'),
        ),
        migrations.AddField(
            model_name='propuestaventa',
            name='tiene_infracciones',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=3, verbose_name='¿Contiene infracciones?'),
        ),
        migrations.AddField(
            model_name='propuestaventa',
            name='titularidad',
            field=models.CharField(blank=True, choices=[('titular', 'Soy titular'), ('no_titular_08', 'No soy titular, tengo el 08')], max_length=20, verbose_name='Titularidad'),
        ),
    ]
